### ISSUE TITLE
[Question] How can we help test?

### ISSUE THREAD

**Issue by etyp** [tulip/oplogtoredis#18]
Hey @benweissmann this project seems pretty awesome. We've just put redis oplog into our production app and are already seeing some exciting improvements.

While nobody on our team has much go experience, we do have an app with plenty of concurrent users + places where we need to support out of band mongo changes.

Is there anything we can do to help out with testing the project and helping to get it closer to production ready?

**Comment by benweissmann** [comment]
Hi @etyp, thanks for asking! The best thing to do is to set up `oplogtoredis` and try it out with production-like traffic -- if you have a staging/test environment with its own Mongo and Redis database, you can run oplogtoredis there, and then follow the instructions (https://github.com/tulip/oplogtoredis#configuring-redis-oplog) to configure redis-oplog. You can also try it out on your own computer or wherever you do development. 

You can also try running oplogtoredis in your production environment, but not configure redis-oplog to read those messages. This lets us test the stability of oplogtoredis in a production environment without actually affecting production behavior. When oplogtoredis publishes a message, it prefixes it with the name of the Mongo database the message is for (e.g. a write to the `foo` collection in the `bar` database will be publishes to the channels `bar.foo` and `bar.foo::theidofthedocument`, whereas redis-oplog by default is looking at the channels `foo` and `foo::theidofthedocument` -- that's why the README has you configure a prefix in redis-oplog). That means that if you're running redis-oplog in its default configuration, without setting up the prefix, it will ignore the messages from oplogtoredis. If you do try it out like this, you should report back with how stable it is -- whether it crashes under and condition, or if the logs report errors or warnings. We've been running it this way in our production environment for about 2 weeks now without issue, but the more production environments we test it out in, the better!

Finally, it would be great to get some feedback on the README, especially the documentation for setting up, configuring, and operation oplogtoredis in production.

At Tulip, we'll be starting to use this to serve a portion of our production traffic in the next 1-2 weeks or so. Once we're serving all of our production traffic with it (in 3-4 weeks, assuming no major issues), I'll tag a `0.1.0` release and feel comfortable recommending that other people use it in production. That said, we've been running it as described above just to test the stability, and it's been working well for the past several weeks, so if you find that it works for you, it's certainly feature-complete and should be ready to serve production traffic.

Let me know how it goes for you, and thanks for the help!

**Comment by benweissmann** [comment]
Closing this out -- we've been using `oplogtoredis` in production for a few months now with no issues.  I've tagged a `v1.0.0` to indicate this level of stability, and don't plan to add any backwards-incompatible features.
